### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  A jelenleg elérhető qubits számát adja vissza.

  Ez magában foglalja a nem használt qubits; Ez magában foglalja a által `GetQubitsAvailableToUse`visszaadott qubits.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Egy `borrowing` utasításban lefoglalt qubits száma.

      Ha a használt célszámítógép nem adja meg ezeket az adatokat, akkor `-1` a rendszer visszaadja.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 99dd2afb66c334b112a2ee511b0437281da6b888
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682411"
