### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: microsoft.quantum.environment
summary: >-
  A jelenleg elérhető qubits számát adja vissza.

  Ez magában foglalja a nem használt qubits; Ez magában foglalja a által visszaadott qubits `GetQubitsAvailableToUse` .
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Egy utasításban lefoglalt qubits száma `borrowing` .

      Ha a használt célszámítógép nem adja meg ezeket az adatokat, akkor a `-1` rendszer visszaadja.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 18e68548e9f344a70dac95f70528a8b3e87f5909
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91478069"
