### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: A jelenleg elérhető qubits számát adja vissza.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: A jelenleg használható qubits számát adja vissza.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Ezek a függvények információt nyújtanak arról a környezetről, amelyben a kvantum-számítás történik.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201444"
