### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: A jelenleg használható qubits számát adja vissza.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Egy `using`-utasításban foglalható qubits száma.

      Ha a használt célszámítógép nem adja meg ezeket az adatokat, akkor a rendszer `-1` visszaadja.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 1cb1331aa26ec9755a9e379336f46387b61bb0ae
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73230466"
