### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesparsemulticonfigurationalstate
name: PrepareSparseMultiConfigurationalState
type: operation
namespace: Microsoft.Quantum.Chemistry.JordanWigner
summary: Ritka, többkonfigurációs állapot előkészítése próbaverziós állapothoz a kezdeti próbaverziós állapotba való felizgatás hozzáadásával.
syntax: 'operation PrepareSparseMultiConfigurationalState (initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[]) : Unit'
input:
  content: '(initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[])'
  types:
  - name: initialStatePreparation
    summary: A kezdeti próbaverziós állapot előkészítésének egységesje.
    isOperation: true
    input:
      types:
      - isArray: true
        isPrimitive: true
        uid: Qubit
    output:
      types:
      - isPrimitive: true
        uid: Unit
  - name: excitations
    summary: A gerjesztő a gerjesztés és a qubit indexek által képviselt kezdeti próbaverziós állapot izgatása.
    isArray: true
    uid: microsoft.quantum.chemistry.jordanwigner.jordanwignerinputstate
  - name: qubits
    summary: A Hamilton qubits.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
ms.openlocfilehash: c97f5e7ec8a4cc26b4fb173414526363db424293
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: hu-HU
ms.lasthandoff: 10/31/2019
ms.locfileid: "73231809"
