### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesingleconfigurationalstatesinglesiteoccupation
name: PrepareSingleConfigurationalStateSingleSiteOccupation
type: operation
namespace: Microsoft.Quantum.Chemistry.JordanWigner
summary: Próbaverziós állapot egyszerű állapotának előkészítése a spin-orbits elfoglalásával
syntax: 'operation PrepareSingleConfigurationalStateSingleSiteOccupation (qubitIndices : Int[], qubits : Qubit[]) : Unit'
input:
  content: '(qubitIndices : Int[], qubits : Qubit[])'
  types:
  - name: qubitIndices
    summary: Az elektronok által foglalt qubits indexek.
    isArray: true
    isPrimitive: true
    uid: Int
  - name: qubits
    summary: A Hamilton qubits.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
functors:
- Adjoint
- Controlled
metadata:
  ms.openlocfilehash: 1f4d073162e2896e5c2c7f8503e524aacc0b3101
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82664952"
